# Generated by Django 5.0.3 on 2024-03-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lines',
            old_name='length',
            new_name='Length',
        ),
        migrations.RenameField(
            model_name='lines',
            old_name='end_ID',
            new_name='endID',
        ),
        migrations.RenameField(
            model_name='lines',
            old_name='start_ID',
            new_name='startID',
        ),
        migrations.RenameField(
            model_name='points',
            old_name='Xcoordinate',
            new_name='pointX',
        ),
        migrations.RenameField(
            model_name='points',
            old_name='Ycoordinate',
            new_name='pointY',
        ),
    ]
