# Generated by Django 5.0.3 on 2024-03-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navApp', '0002_rename_length_lines_length_rename_end_id_lines_endid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lines',
            name='Length',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='lines',
            name='endID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lines',
            name='startID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mapimage',
            name='floor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mapimage',
            name='path',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mapimage',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='points',
            name='pointX',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='points',
            name='pointY',
            field=models.FloatField(null=True),
        ),
    ]
