# Generated by Django 5.0.3 on 2024-03-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navApp', '0003_alter_lines_length_alter_lines_endid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapimage',
            name='path',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
