# Generated by Django 5.0.3 on 2024-03-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navApp', '0005_alter_mapimage_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertices', models.IntegerField()),
                ('graph', models.CharField(max_length=10000)),
            ],
        ),
    ]
