# Generated by Django 5.0.3 on 2024-03-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navApp', '0006_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
