# Generated by Django 5.0.3 on 2024-03-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navApp', '0007_graph_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='title',
        ),
        migrations.AddField(
            model_name='graph',
            name='floor',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='points',
            name='floor',
            field=models.IntegerField(null=True),
        ),
    ]
