# Generated by Django 5.0.3 on 2024-03-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navApp', '0008_remove_graph_title_graph_floor_points_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='lines',
            name='floor',
            field=models.IntegerField(null=True),
        ),
    ]
