# Generated by Django 5.0.3 on 2024-03-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navApp', '0009_lines_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='alt',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='points',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
