# Generated by Django 5.0.3 on 2024-03-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navApp', '0010_points_alt_alter_points_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
