# Generated by Django 5.0.3 on 2024-03-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navApp', '0011_points_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='id',
        ),
        migrations.AlterField(
            model_name='graph',
            name='floor',
            field=models.IntegerField(default='0', primary_key=True, serialize=False),
        ),
    ]
