# Generated by Django 5.0.3 on 2024-03-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navApp', '0012_remove_graph_id_alter_graph_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapimage',
            name='path',
            field=models.ImageField(null=True, upload_to='PathIn/navApp/static/img'),
        ),
    ]
