# Generated by Django 5.0.3 on 2024-03-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navApp', '0013_alter_mapimage_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapimage',
            name='path',
            field=models.ImageField(null=True, upload_to='navApp/static/img'),
        ),
    ]
