# Generated by Django 5.0.3 on 2024-03-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navApp', '0015_alter_mapimage_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapimage',
            name='path',
            field=models.ImageField(null=True, upload_to='static/img/'),
        ),
    ]
